INSERT INTO tCartes
(idSerie, idRarete, idType, numSerie)
VALUES
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),1),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),2),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),3),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),4),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),5),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),6),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),7),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),8),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),9),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),10),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),11),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),12),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),13),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),14),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),15),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),16),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),17),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),18),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),19),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),20),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),21),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),22),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),23),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),24),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),25),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),26),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),27),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),28),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),29),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),30),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),31),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),32),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),33),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),34),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),35),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),36),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),37),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),38),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),39),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),40),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),41),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),42),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),43),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),44),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),45),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),46),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),47),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),48),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),49),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),50),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),51),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),52),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),53),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),54),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),55),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),56),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),57),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),58),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),59),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),60),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),61),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),62),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),63),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),64),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),65),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),66),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),67),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),68),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fire"),69),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),70),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),71),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),72),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),73),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),74),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),75),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),76),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),77),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),78),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),79),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),80),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),81),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),82),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),83),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),84),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),85),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),86),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),87),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),88),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),89),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),90),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),91),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),92),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),93),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),94),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),95),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),96),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),97),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),98),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fire"),99),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),100),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),101),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),102),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),103),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),104),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),105),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),106),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),107),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),108),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),109),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),110),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),111),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),112),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),113),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),114),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),115),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),116),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),117),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),118),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),119),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),120),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),121),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),122),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),123),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),124),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Fighting"),125),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Fire"),126),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Grass"),127),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Lightning"),128),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Psychic"),129),
((SELECT idSerie FROM tSeries WHERE nom="Base Set 2"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Water"),130);

INSERT INTO tCartesPokemons
(idPokemon, idCarte)
VALUES
((SELECT idPokemon FROM tPokemons WHERE nom="Alakazam"),(SELECT idCarte FROM tCartes WHERE numSerie=1 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Blastoise"),(SELECT idCarte FROM tCartes WHERE numSerie=2 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Chansey"),(SELECT idCarte FROM tCartes WHERE numSerie=3 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Charizard"),(SELECT idCarte FROM tCartes WHERE numSerie=4 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Clefable"),(SELECT idCarte FROM tCartes WHERE numSerie=5 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Clefairy"),(SELECT idCarte FROM tCartes WHERE numSerie=6 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Gyarados"),(SELECT idCarte FROM tCartes WHERE numSerie=7 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Hitmonchan"),(SELECT idCarte FROM tCartes WHERE numSerie=8 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Magneton"),(SELECT idCarte FROM tCartes WHERE numSerie=9 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Mewtwo"),(SELECT idCarte FROM tCartes WHERE numSerie=10 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoking"),(SELECT idCarte FROM tCartes WHERE numSerie=11 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoqueen"),(SELECT idCarte FROM tCartes WHERE numSerie=12 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Ninetales"),(SELECT idCarte FROM tCartes WHERE numSerie=13 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Pidgeot"),(SELECT idCarte FROM tCartes WHERE numSerie=14 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Poliwrath"),(SELECT idCarte FROM tCartes WHERE numSerie=15 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Raichu"),(SELECT idCarte FROM tCartes WHERE numSerie=16 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Scyther"),(SELECT idCarte FROM tCartes WHERE numSerie=17 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Venusaur"),(SELECT idCarte FROM tCartes WHERE numSerie=18 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Wigglytuff"),(SELECT idCarte FROM tCartes WHERE numSerie=19 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Zapdos"),(SELECT idCarte FROM tCartes WHERE numSerie=20 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Beedrill"),(SELECT idCarte FROM tCartes WHERE numSerie=21 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Dragonair"),(SELECT idCarte FROM tCartes WHERE numSerie=22 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Dugtrio"),(SELECT idCarte FROM tCartes WHERE numSerie=23 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Electabuzz"),(SELECT idCarte FROM tCartes WHERE numSerie=24 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Electrode"),(SELECT idCarte FROM tCartes WHERE numSerie=25 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Kangaskhan"),(SELECT idCarte FROM tCartes WHERE numSerie=26 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Mr. Mime"),(SELECT idCarte FROM tCartes WHERE numSerie=27 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Pidgeotto"),(SELECT idCarte FROM tCartes WHERE numSerie=28 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Pinsir"),(SELECT idCarte FROM tCartes WHERE numSerie=29 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Snorlax"),(SELECT idCarte FROM tCartes WHERE numSerie=30 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Venomoth"),(SELECT idCarte FROM tCartes WHERE numSerie=31 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Victreebel"),(SELECT idCarte FROM tCartes WHERE numSerie=32 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Arcanine"),(SELECT idCarte FROM tCartes WHERE numSerie=33 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Butterfree"),(SELECT idCarte FROM tCartes WHERE numSerie=34 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Charmeleon"),(SELECT idCarte FROM tCartes WHERE numSerie=35 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Dewgong"),(SELECT idCarte FROM tCartes WHERE numSerie=36 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Dodrio"),(SELECT idCarte FROM tCartes WHERE numSerie=37 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Dratini"),(SELECT idCarte FROM tCartes WHERE numSerie=38 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Exeggutor"),(SELECT idCarte FROM tCartes WHERE numSerie=39 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Farfetch'd"),(SELECT idCarte FROM tCartes WHERE numSerie=40 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Fearow"),(SELECT idCarte FROM tCartes WHERE numSerie=41 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Growlithe"),(SELECT idCarte FROM tCartes WHERE numSerie=42 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Haunter"),(SELECT idCarte FROM tCartes WHERE numSerie=43 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Ivysaur"),(SELECT idCarte FROM tCartes WHERE numSerie=44 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Jynx"),(SELECT idCarte FROM tCartes WHERE numSerie=45 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Kadabra"),(SELECT idCarte FROM tCartes WHERE numSerie=46 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Kakuna"),(SELECT idCarte FROM tCartes WHERE numSerie=47 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Lickitung"),(SELECT idCarte FROM tCartes WHERE numSerie=48 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Machoke"),(SELECT idCarte FROM tCartes WHERE numSerie=49 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Magikarp"),(SELECT idCarte FROM tCartes WHERE numSerie=50 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Magmar"),(SELECT idCarte FROM tCartes WHERE numSerie=51 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Marowak"),(SELECT idCarte FROM tCartes WHERE numSerie=52 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidorina"),(SELECT idCarte FROM tCartes WHERE numSerie=53 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidorino"),(SELECT idCarte FROM tCartes WHERE numSerie=54 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Parasect"),(SELECT idCarte FROM tCartes WHERE numSerie=55 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Persian"),(SELECT idCarte FROM tCartes WHERE numSerie=56 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Poliwhirl"),(SELECT idCarte FROM tCartes WHERE numSerie=57 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Raticate"),(SELECT idCarte FROM tCartes WHERE numSerie=58 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Rhydon"),(SELECT idCarte FROM tCartes WHERE numSerie=59 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Seaking"),(SELECT idCarte FROM tCartes WHERE numSerie=60 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Seel"),(SELECT idCarte FROM tCartes WHERE numSerie=61 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Tauros"),(SELECT idCarte FROM tCartes WHERE numSerie=62 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Wartortle"),(SELECT idCarte FROM tCartes WHERE numSerie=63 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Weepinbell"),(SELECT idCarte FROM tCartes WHERE numSerie=64 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Abra"),(SELECT idCarte FROM tCartes WHERE numSerie=65 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Bellsprout"),(SELECT idCarte FROM tCartes WHERE numSerie=66 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Bulbasaur"),(SELECT idCarte FROM tCartes WHERE numSerie=67 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Caterpie"),(SELECT idCarte FROM tCartes WHERE numSerie=68 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Charmander"),(SELECT idCarte FROM tCartes WHERE numSerie=69 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Cubone"),(SELECT idCarte FROM tCartes WHERE numSerie=70 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Diglett"),(SELECT idCarte FROM tCartes WHERE numSerie=71 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Doduo"),(SELECT idCarte FROM tCartes WHERE numSerie=72 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Drowzee"),(SELECT idCarte FROM tCartes WHERE numSerie=73 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Exeggcute"),(SELECT idCarte FROM tCartes WHERE numSerie=74 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Gastly"),(SELECT idCarte FROM tCartes WHERE numSerie=75 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Goldeen"),(SELECT idCarte FROM tCartes WHERE numSerie=76 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Jigglypuff"),(SELECT idCarte FROM tCartes WHERE numSerie=77 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Machop"),(SELECT idCarte FROM tCartes WHERE numSerie=78 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Magnemite"),(SELECT idCarte FROM tCartes WHERE numSerie=79 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Meowth"),(SELECT idCarte FROM tCartes WHERE numSerie=80 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Metapod"),(SELECT idCarte FROM tCartes WHERE numSerie=81 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoran/e29980/"),(SELECT idCarte FROM tCartes WHERE numSerie=82 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoran/e29982/"),(SELECT idCarte FROM tCartes WHERE numSerie=83 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Onix"),(SELECT idCarte FROM tCartes WHERE numSerie=84 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Paras"),(SELECT idCarte FROM tCartes WHERE numSerie=85 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Pidgey"),(SELECT idCarte FROM tCartes WHERE numSerie=86 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Pikachu"),(SELECT idCarte FROM tCartes WHERE numSerie=87 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Poliwag"),(SELECT idCarte FROM tCartes WHERE numSerie=88 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Rattata"),(SELECT idCarte FROM tCartes WHERE numSerie=89 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Rhyhorn"),(SELECT idCarte FROM tCartes WHERE numSerie=90 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Sandshrew"),(SELECT idCarte FROM tCartes WHERE numSerie=91 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Spearow"),(SELECT idCarte FROM tCartes WHERE numSerie=92 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Squirtle"),(SELECT idCarte FROM tCartes WHERE numSerie=93 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Starmie"),(SELECT idCarte FROM tCartes WHERE numSerie=94 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Staryu"),(SELECT idCarte FROM tCartes WHERE numSerie=95 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Tangela"),(SELECT idCarte FROM tCartes WHERE numSerie=96 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Venonat"),(SELECT idCarte FROM tCartes WHERE numSerie=97 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Voltorb"),(SELECT idCarte FROM tCartes WHERE numSerie=98 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Vulpix"),(SELECT idCarte FROM tCartes WHERE numSerie=99 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Weedle"),(SELECT idCarte FROM tCartes WHERE numSerie=100 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2")));

INSERT INTO tCartesTrainers
(idTrainer, idCarte)
VALUES
((SELECT idTrainer FROM tTrainers WHERE nom="Computer Search"),(SELECT idCarte FROM tCartes WHERE numSerie=101 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Imposter Professor Oak"),(SELECT idCarte FROM tCartes WHERE numSerie=102 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Item Finder"),(SELECT idCarte FROM tCartes WHERE numSerie=103 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Lass"),(SELECT idCarte FROM tCartes WHERE numSerie=104 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokémon Breeder"),(SELECT idCarte FROM tCartes WHERE numSerie=105 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokémon Trader"),(SELECT idCarte FROM tCartes WHERE numSerie=106 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Scoop Up"),(SELECT idCarte FROM tCartes WHERE numSerie=107 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Super Energy Removal"),(SELECT idCarte FROM tCartes WHERE numSerie=108 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Defender"),(SELECT idCarte FROM tCartes WHERE numSerie=109 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Energy Retrieval"),(SELECT idCarte FROM tCartes WHERE numSerie=110 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Full Heal"),(SELECT idCarte FROM tCartes WHERE numSerie=111 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Maintenance"),(SELECT idCarte FROM tCartes WHERE numSerie=112 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="PlusPower"),(SELECT idCarte FROM tCartes WHERE numSerie=113 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokémon Center"),(SELECT idCarte FROM tCartes WHERE numSerie=114 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokédex"),(SELECT idCarte FROM tCartes WHERE numSerie=115 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Professor Oak"),(SELECT idCarte FROM tCartes WHERE numSerie=116 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Super Potion"),(SELECT idCarte FROM tCartes WHERE numSerie=117 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Bill"),(SELECT idCarte FROM tCartes WHERE numSerie=118 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Energy Removal"),(SELECT idCarte FROM tCartes WHERE numSerie=119 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Gust of Wind"),(SELECT idCarte FROM tCartes WHERE numSerie=120 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Poké Ball"),(SELECT idCarte FROM tCartes WHERE numSerie=121 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Potion"),(SELECT idCarte FROM tCartes WHERE numSerie=122 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Switch"),(SELECT idCarte FROM tCartes WHERE numSerie=123 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2")));

INSERT INTO tCartesEnergies
(idEnergie, idCarte)
VALUES
((SELECT idEnergie FROM tEnergies WHERE nom="Double Colorless Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=124 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Fighting Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=125 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Fire Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=126 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Grass Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=127 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Lightning Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=128 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Psychic Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=129 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Water Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=130 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set 2")));