INSERT INTO tCartes
(idSerie, idRarete, idType, numSerie)
VALUES
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),1),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),2),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),3),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),4),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),5),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),6),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),7),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),8),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),9),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),10),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),11),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),12),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),13),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),14),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),15),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),16),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),17),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),18),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),19),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),20),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),21),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),22),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),23),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),24),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),25),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),26),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),27),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),28),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),29),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),30),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),31),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),32),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),33),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),34),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),35),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),36),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),37),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),38),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),39),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),40),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),41),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),42),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),43),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),44),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),45),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fire"),46),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),47),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),48),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),49),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),50),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),51),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),52),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),53),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),54),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),55),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),56),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),57),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),58),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),59),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fire"),60),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),61),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),62),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),63),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),64),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),65),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),66),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),67),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fire"),68),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),69),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),70),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),71),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),72),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),73),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),74),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),75),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),76),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),77),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),78),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),79),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),80),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),81),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),82),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),83),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),84),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),85),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),86),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),87),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),88),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),89),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),90),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),91),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),92),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),93),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),94),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),95),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),96),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Fighting"),97),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Fire"),98),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Grass"),99),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Lightning"),100),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Psychic"),101),
((SELECT idSerie FROM tSeries WHERE nom="Base Set"),(SELECT idRarete FROM tRaretes WHERE nom="None"),(SELECT idType FROM tTypes WHERE nom="Water"),102);

INSERT INTO tCartesPokemons
(idPokemon, idCarte)
VALUES
((SELECT idPokemon FROM tPokemons WHERE nom="Alakazam"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=1)),
((SELECT idPokemon FROM tPokemons WHERE nom="Blastoise"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=2)),
((SELECT idPokemon FROM tPokemons WHERE nom="Chansey"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=3)),
((SELECT idPokemon FROM tPokemons WHERE nom="Charizard"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=4)),
((SELECT idPokemon FROM tPokemons WHERE nom="Clefairy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=5)),
((SELECT idPokemon FROM tPokemons WHERE nom="Gyarados"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=6)),
((SELECT idPokemon FROM tPokemons WHERE nom="Hitmonchan"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=7)),
((SELECT idPokemon FROM tPokemons WHERE nom="Machamp"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=8)),
((SELECT idPokemon FROM tPokemons WHERE nom="Magneton"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=9)),
((SELECT idPokemon FROM tPokemons WHERE nom="Mewtwo"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=10)),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoking"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=11)),
((SELECT idPokemon FROM tPokemons WHERE nom="Ninetales"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=12)),
((SELECT idPokemon FROM tPokemons WHERE nom="Poliwrath"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=13)),
((SELECT idPokemon FROM tPokemons WHERE nom="Raichu"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=14)),
((SELECT idPokemon FROM tPokemons WHERE nom="Venusaur"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=15)),
((SELECT idPokemon FROM tPokemons WHERE nom="Zapdos"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=16)),
((SELECT idPokemon FROM tPokemons WHERE nom="Beedrill"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=17)),
((SELECT idPokemon FROM tPokemons WHERE nom="Dragonair"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=18)),
((SELECT idPokemon FROM tPokemons WHERE nom="Dugtrio"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=19)),
((SELECT idPokemon FROM tPokemons WHERE nom="Electabuzz"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=20)),
((SELECT idPokemon FROM tPokemons WHERE nom="Electrode"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=21)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pidgeotto"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=22)),
((SELECT idPokemon FROM tPokemons WHERE nom="Arcanine"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=23)),
((SELECT idPokemon FROM tPokemons WHERE nom="Charmeleon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=24)),
((SELECT idPokemon FROM tPokemons WHERE nom="Dewgong"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=25)),
((SELECT idPokemon FROM tPokemons WHERE nom="Dratini"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=26)),
((SELECT idPokemon FROM tPokemons WHERE nom="Farfetch'd"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=27)),
((SELECT idPokemon FROM tPokemons WHERE nom="Growlithe"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=28)),
((SELECT idPokemon FROM tPokemons WHERE nom="Haunter"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=29)),
((SELECT idPokemon FROM tPokemons WHERE nom="Ivysaur"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=30)),
((SELECT idPokemon FROM tPokemons WHERE nom="Jynx"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=31)),
((SELECT idPokemon FROM tPokemons WHERE nom="Kadabra"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=32)),
((SELECT idPokemon FROM tPokemons WHERE nom="Kakuna"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=33)),
((SELECT idPokemon FROM tPokemons WHERE nom="Machoke"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=34)),
((SELECT idPokemon FROM tPokemons WHERE nom="Magikarp"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=35)),
((SELECT idPokemon FROM tPokemons WHERE nom="Magmar"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=36)),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidorino"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=37)),
((SELECT idPokemon FROM tPokemons WHERE nom="Poliwhirl"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=38)),
((SELECT idPokemon FROM tPokemons WHERE nom="Porygon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=39)),
((SELECT idPokemon FROM tPokemons WHERE nom="Raticate"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=40)),
((SELECT idPokemon FROM tPokemons WHERE nom="Seel"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=41)),
((SELECT idPokemon FROM tPokemons WHERE nom="Wartortle"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=42)),
((SELECT idPokemon FROM tPokemons WHERE nom="Abra"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=43)),
((SELECT idPokemon FROM tPokemons WHERE nom="Bulbasaur"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=44)),
((SELECT idPokemon FROM tPokemons WHERE nom="Caterpie"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=45)),
((SELECT idPokemon FROM tPokemons WHERE nom="Charmander"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=46)),
((SELECT idPokemon FROM tPokemons WHERE nom="Diglett"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=47)),
((SELECT idPokemon FROM tPokemons WHERE nom="Doduo"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=48)),
((SELECT idPokemon FROM tPokemons WHERE nom="Drowzee"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=49)),
((SELECT idPokemon FROM tPokemons WHERE nom="Gastly"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=50)),
((SELECT idPokemon FROM tPokemons WHERE nom="Koffing"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=51)),
((SELECT idPokemon FROM tPokemons WHERE nom="Machop"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=52)),
((SELECT idPokemon FROM tPokemons WHERE nom="Magnemite"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=53)),
((SELECT idPokemon FROM tPokemons WHERE nom="Metapod"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=54)),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoran/e29982/"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=55)),
((SELECT idPokemon FROM tPokemons WHERE nom="Onix"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=56)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pidgey"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=57)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pikachu"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=58)),
((SELECT idPokemon FROM tPokemons WHERE nom="Poliwag"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=59)),
((SELECT idPokemon FROM tPokemons WHERE nom="Ponyta"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=60)),
((SELECT idPokemon FROM tPokemons WHERE nom="Rattata"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=61)),
((SELECT idPokemon FROM tPokemons WHERE nom="Sandshrew"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=62)),
((SELECT idPokemon FROM tPokemons WHERE nom="Squirtle"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=63)),
((SELECT idPokemon FROM tPokemons WHERE nom="Starmie"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=64)),
((SELECT idPokemon FROM tPokemons WHERE nom="Staryu"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=65)),
((SELECT idPokemon FROM tPokemons WHERE nom="Tangela"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=66)),
((SELECT idPokemon FROM tPokemons WHERE nom="Voltorb"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=67)),
((SELECT idPokemon FROM tPokemons WHERE nom="Vulpix"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=68)),
((SELECT idPokemon FROM tPokemons WHERE nom="Weedle"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=69));

INSERT INTO tCartesTrainers
(idTrainer, idCarte)
VALUES
((SELECT idTrainer FROM tTrainers WHERE nom="Clefairy Doll"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=70)),
((SELECT idTrainer FROM tTrainers WHERE nom="Computer Search"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=71)),
((SELECT idTrainer FROM tTrainers WHERE nom="Devolution Spray"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=72)),
((SELECT idTrainer FROM tTrainers WHERE nom="Impostor Professor Oak"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=73)),
((SELECT idTrainer FROM tTrainers WHERE nom="Item Finder"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=74)),
((SELECT idTrainer FROM tTrainers WHERE nom="Lass"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=75)),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokémon Breeder"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=76)),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokémon Trader"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=77)),
((SELECT idTrainer FROM tTrainers WHERE nom="Scoop Up"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=78)),
((SELECT idTrainer FROM tTrainers WHERE nom="Super Energy Removal"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=79)),
((SELECT idTrainer FROM tTrainers WHERE nom="Defender"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=80)),
((SELECT idTrainer FROM tTrainers WHERE nom="Energy Retrieval"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=81)),
((SELECT idTrainer FROM tTrainers WHERE nom="Full Heal"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=82)),
((SELECT idTrainer FROM tTrainers WHERE nom="Maintenance"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=83)),
((SELECT idTrainer FROM tTrainers WHERE nom="PlusPower"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=84)),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokémon Center"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=85)),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokémon Flute"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=86)),
((SELECT idTrainer FROM tTrainers WHERE nom="Pokédex"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=87)),
((SELECT idTrainer FROM tTrainers WHERE nom="Professor Oak"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=88)),
((SELECT idTrainer FROM tTrainers WHERE nom="Revive"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=89)),
((SELECT idTrainer FROM tTrainers WHERE nom="Super Potion"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=90)),
((SELECT idTrainer FROM tTrainers WHERE nom="Bill"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=91)),
((SELECT idTrainer FROM tTrainers WHERE nom="Energy Removal"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=92)),
((SELECT idTrainer FROM tTrainers WHERE nom="Gust of Wind"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=93)),
((SELECT idTrainer FROM tTrainers WHERE nom="Potion"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=94)),
((SELECT idTrainer FROM tTrainers WHERE nom="Switch"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=95));

INSERT INTO tCartesEnergies
(idEnergie, idCarte)
VALUES
((SELECT idEnergie FROM tEnergies WHERE nom="Double Colorless Energy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=96)),
((SELECT idEnergie FROM tEnergies WHERE nom="Fighting Energy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=97)),
((SELECT idEnergie FROM tEnergies WHERE nom="Fire Energy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=98)),
((SELECT idEnergie FROM tEnergies WHERE nom="Grass Energy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=99)),
((SELECT idEnergie FROM tEnergies WHERE nom="Lightning Energy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=100)),
((SELECT idEnergie FROM tEnergies WHERE nom="Psychic Energy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=101)),
((SELECT idEnergie FROM tEnergies WHERE nom="Water Energy"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Base Set") AND numSerie=102));