INSERT INTO tCartes
(idSerie, idRarete, idType, numSerie)
VALUES
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),1),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),2),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),3),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),4),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),5),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),6),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),7),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),8),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),9),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),10),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),11),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),12),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),13),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),14),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),15),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),16),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),17),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),18),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),19),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),20),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),21),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),22),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),23),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),24),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),25),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),26),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),27),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),28),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),29),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),30),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),31),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),32),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),33),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),34),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),35),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),36),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),37),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),38),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),39),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),40),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),41),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),42),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),43),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),44),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),45),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),46),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),47),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),48),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),49),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),50),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),51),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),52),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),53),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),54),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),55),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),56),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),57),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),58),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),59),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),60),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),61),
((SELECT idSerie FROM tSeries WHERE nom="Fossil"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),62);

INSERT INTO tCartesPokemons
(idPokemon, idCarte)
VALUES
((SELECT idPokemon FROM tPokemons WHERE nom="Aerodactyl"),(SELECT idCarte FROM tCartes WHERE numSerie=1 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Articuno"),(SELECT idCarte FROM tCartes WHERE numSerie=2 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Ditto"),(SELECT idCarte FROM tCartes WHERE numSerie=3 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Dragonite"),(SELECT idCarte FROM tCartes WHERE numSerie=4 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Gengar"),(SELECT idCarte FROM tCartes WHERE numSerie=5 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Haunter"),(SELECT idCarte FROM tCartes WHERE numSerie=6 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Hitmonlee"),(SELECT idCarte FROM tCartes WHERE numSerie=7 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Hypno"),(SELECT idCarte FROM tCartes WHERE numSerie=8 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Kabutops"),(SELECT idCarte FROM tCartes WHERE numSerie=9 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Lapras"),(SELECT idCarte FROM tCartes WHERE numSerie=10 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Magneton"),(SELECT idCarte FROM tCartes WHERE numSerie=11 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Moltres"),(SELECT idCarte FROM tCartes WHERE numSerie=12 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Muk"),(SELECT idCarte FROM tCartes WHERE numSerie=13 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Raichu"),(SELECT idCarte FROM tCartes WHERE numSerie=14 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Zapdos"),(SELECT idCarte FROM tCartes WHERE numSerie=15 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Aerodactyl"),(SELECT idCarte FROM tCartes WHERE numSerie=16 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Articuno"),(SELECT idCarte FROM tCartes WHERE numSerie=17 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Ditto"),(SELECT idCarte FROM tCartes WHERE numSerie=18 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Dragonite"),(SELECT idCarte FROM tCartes WHERE numSerie=19 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Gengar"),(SELECT idCarte FROM tCartes WHERE numSerie=20 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Haunter"),(SELECT idCarte FROM tCartes WHERE numSerie=21 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Hitmonlee"),(SELECT idCarte FROM tCartes WHERE numSerie=22 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Hypno"),(SELECT idCarte FROM tCartes WHERE numSerie=23 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Kabutops"),(SELECT idCarte FROM tCartes WHERE numSerie=24 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Lapras"),(SELECT idCarte FROM tCartes WHERE numSerie=25 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Magneton"),(SELECT idCarte FROM tCartes WHERE numSerie=26 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Moltres"),(SELECT idCarte FROM tCartes WHERE numSerie=27 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Muk"),(SELECT idCarte FROM tCartes WHERE numSerie=28 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Raichu"),(SELECT idCarte FROM tCartes WHERE numSerie=29 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Zapdos"),(SELECT idCarte FROM tCartes WHERE numSerie=30 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Arbok"),(SELECT idCarte FROM tCartes WHERE numSerie=31 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Cloyster"),(SELECT idCarte FROM tCartes WHERE numSerie=32 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Gastly"),(SELECT idCarte FROM tCartes WHERE numSerie=33 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Golbat"),(SELECT idCarte FROM tCartes WHERE numSerie=34 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Golduck"),(SELECT idCarte FROM tCartes WHERE numSerie=35 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Golem"),(SELECT idCarte FROM tCartes WHERE numSerie=36 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Graveler"),(SELECT idCarte FROM tCartes WHERE numSerie=37 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Kingler"),(SELECT idCarte FROM tCartes WHERE numSerie=38 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Magmar"),(SELECT idCarte FROM tCartes WHERE numSerie=39 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Omastar"),(SELECT idCarte FROM tCartes WHERE numSerie=40 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Sandslash"),(SELECT idCarte FROM tCartes WHERE numSerie=41 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Seadra"),(SELECT idCarte FROM tCartes WHERE numSerie=42 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Slowbro"),(SELECT idCarte FROM tCartes WHERE numSerie=43 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Tentacruel"),(SELECT idCarte FROM tCartes WHERE numSerie=44 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Weezing"),(SELECT idCarte FROM tCartes WHERE numSerie=45 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Ekans"),(SELECT idCarte FROM tCartes WHERE numSerie=46 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Geodude"),(SELECT idCarte FROM tCartes WHERE numSerie=47 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Grimer"),(SELECT idCarte FROM tCartes WHERE numSerie=48 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Horsea"),(SELECT idCarte FROM tCartes WHERE numSerie=49 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Kabuto"),(SELECT idCarte FROM tCartes WHERE numSerie=50 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Krabby"),(SELECT idCarte FROM tCartes WHERE numSerie=51 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Omanyte"),(SELECT idCarte FROM tCartes WHERE numSerie=52 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Psyduck"),(SELECT idCarte FROM tCartes WHERE numSerie=53 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Shellder"),(SELECT idCarte FROM tCartes WHERE numSerie=54 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Slowpoke"),(SELECT idCarte FROM tCartes WHERE numSerie=55 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Tentacool"),(SELECT idCarte FROM tCartes WHERE numSerie=56 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idPokemon FROM tPokemons WHERE nom="Zubat"),(SELECT idCarte FROM tCartes WHERE numSerie=57 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil")));

INSERT INTO tCartesTrainers
(idTrainer, idCarte)
VALUES
((SELECT idTrainer FROM tTrainers WHERE nom="Mr. Fuji"),(SELECT idCarte FROM tCartes WHERE numSerie=58 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Energy Search"),(SELECT idCarte FROM tCartes WHERE numSerie=59 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Gambler"),(SELECT idCarte FROM tCartes WHERE numSerie=60 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Recycle"),(SELECT idCarte FROM tCartes WHERE numSerie=61 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Mysterious Fossil"),(SELECT idCarte FROM tCartes WHERE numSerie=62 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Fossil")));