INSERT INTO tCartes
(idSerie, idRarete, idType, numSerie)
VALUES
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),1),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),2),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),3),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),4),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),5),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),6),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),7),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),8),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),9),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),10),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),11),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),12),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),13),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),14),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),15),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),16),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),17),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),18),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),19),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),20),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),21),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),22),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),23),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),24),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),25),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),26),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),27),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),28),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),29),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),30),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),31),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),32),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),33),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),34),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),35),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),36),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),37),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),38),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),39),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),40),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),41),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),42),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),43),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),44),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),45),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),46),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),47),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),48),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),49),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),50),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),51),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),52),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),53),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),54),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),55),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),56),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),57),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),58),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),59),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),60),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),61),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),62),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),63),
((SELECT idSerie FROM tSeries WHERE nom="Jungle"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),64);


INSERT INTO tCartesPokemons
(idPokemon, idCarte)
VALUES
((SELECT idPokemon FROM tPokemons WHERE nom="Clefable"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=1)),
((SELECT idPokemon FROM tPokemons WHERE nom="Electrode"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=2)),
((SELECT idPokemon FROM tPokemons WHERE nom="Flareon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=3)),
((SELECT idPokemon FROM tPokemons WHERE nom="Jolteon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=4)),
((SELECT idPokemon FROM tPokemons WHERE nom="Kangaskhan"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=5)),
((SELECT idPokemon FROM tPokemons WHERE nom="Mr. Mime"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=6)),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoqueen"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=7)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pidgeot"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=8)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pinsir"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=9)),
((SELECT idPokemon FROM tPokemons WHERE nom="Scyther"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=10)),
((SELECT idPokemon FROM tPokemons WHERE nom="Snorlax"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=11)),
((SELECT idPokemon FROM tPokemons WHERE nom="Vaporeon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=12)),
((SELECT idPokemon FROM tPokemons WHERE nom="Venomoth"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=13)),
((SELECT idPokemon FROM tPokemons WHERE nom="Victreebel"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=14)),
((SELECT idPokemon FROM tPokemons WHERE nom="Vileplume"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=15)),
((SELECT idPokemon FROM tPokemons WHERE nom="Wigglytuff"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=16)),
((SELECT idPokemon FROM tPokemons WHERE nom="Clefable"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=17)),
((SELECT idPokemon FROM tPokemons WHERE nom="Electrode"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=18)),
((SELECT idPokemon FROM tPokemons WHERE nom="Flareon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=19)),
((SELECT idPokemon FROM tPokemons WHERE nom="Jolteon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=20)),
((SELECT idPokemon FROM tPokemons WHERE nom="Kangaskhan"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=21)),
((SELECT idPokemon FROM tPokemons WHERE nom="Mr. Mime"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=22)),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoqueen"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=23)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pidgeot"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=24)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pinsir"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=25)),
((SELECT idPokemon FROM tPokemons WHERE nom="Scyther"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=26)),
((SELECT idPokemon FROM tPokemons WHERE nom="Snorlax"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=27)),
((SELECT idPokemon FROM tPokemons WHERE nom="Vaporeon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=28)),
((SELECT idPokemon FROM tPokemons WHERE nom="Venomoth"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=29)),
((SELECT idPokemon FROM tPokemons WHERE nom="Victreebel"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=30)),
((SELECT idPokemon FROM tPokemons WHERE nom="Vileplume"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=31)),
((SELECT idPokemon FROM tPokemons WHERE nom="Wigglytuff"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=32)),
((SELECT idPokemon FROM tPokemons WHERE nom="Butterfree"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=33)),
((SELECT idPokemon FROM tPokemons WHERE nom="Dodrio"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=34)),
((SELECT idPokemon FROM tPokemons WHERE nom="Exeggutor"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=35)),
((SELECT idPokemon FROM tPokemons WHERE nom="Fearow"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=36)),
((SELECT idPokemon FROM tPokemons WHERE nom="Gloom"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=37)),
((SELECT idPokemon FROM tPokemons WHERE nom="Lickitung"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=38)),
((SELECT idPokemon FROM tPokemons WHERE nom="Marowak"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=39)),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidorina"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=40)),
((SELECT idPokemon FROM tPokemons WHERE nom="Parasect"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=41)),
((SELECT idPokemon FROM tPokemons WHERE nom="Persian"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=42)),
((SELECT idPokemon FROM tPokemons WHERE nom="Primeape"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=43)),
((SELECT idPokemon FROM tPokemons WHERE nom="Rapidash"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=44)),
((SELECT idPokemon FROM tPokemons WHERE nom="Rhydon"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=45)),
((SELECT idPokemon FROM tPokemons WHERE nom="Seaking"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=46)),
((SELECT idPokemon FROM tPokemons WHERE nom="Tauros"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=47)),
((SELECT idPokemon FROM tPokemons WHERE nom="Weepinbell"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=48)),
((SELECT idPokemon FROM tPokemons WHERE nom="Bellsprout"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=49)),
((SELECT idPokemon FROM tPokemons WHERE nom="Cubone"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=50)),
((SELECT idPokemon FROM tPokemons WHERE nom="Eevee"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=51)),
((SELECT idPokemon FROM tPokemons WHERE nom="Exeggcute"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=52)),
((SELECT idPokemon FROM tPokemons WHERE nom="Goldeen"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=53)),
((SELECT idPokemon FROM tPokemons WHERE nom="Jigglypuff"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=54)),
((SELECT idPokemon FROM tPokemons WHERE nom="Mankey"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=55)),
((SELECT idPokemon FROM tPokemons WHERE nom="Meowth"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=56)),
((SELECT idPokemon FROM tPokemons WHERE nom="Nidoran/e29980/"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=57)),
((SELECT idPokemon FROM tPokemons WHERE nom="Oddish"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=58)),
((SELECT idPokemon FROM tPokemons WHERE nom="Paras"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=59)),
((SELECT idPokemon FROM tPokemons WHERE nom="Pikachu"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=60)),
((SELECT idPokemon FROM tPokemons WHERE nom="Rhyhorn"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=61)),
((SELECT idPokemon FROM tPokemons WHERE nom="Spearow"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=62)),
((SELECT idPokemon FROM tPokemons WHERE nom="Venonat"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=63));

INSERT INTO tCartesTrainers
(idTrainer, idCarte)
VALUES
((SELECT idTrainer FROM tTrainers WHERE nom="Poké Ball"),(SELECT idCarte FROM tCartes WHERE idSerie = (SELECT idSerie FROM tSeries WHERE nom="Jungle") AND numSerie=64));