INSERT INTO tCartes
(idSerie, idRarete, idType, numSerie)
VALUES
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),1),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),2),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),3),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),4),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),5),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),6),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),7),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),8),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),9),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),10),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),11),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),12),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),13),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),14),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),15),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),16),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Rainbow"),17),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),18),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),19),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),20),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fire"),21),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Colorless"),22),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),23),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),24),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Water"),25),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),26),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Fighting"),27),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),28),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Psychic"),29),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),30),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Grass"),31),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),32),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),33),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Lightning"),34),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),35),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),36),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),37),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Lightning"),38),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Psychic"),39),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),40),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Grass"),41),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),42),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fighting"),43),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Fire"),44),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),45),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),46),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Water"),47),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),48),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),49),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fire"),50),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),51),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),52),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),53),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),54),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),55),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),56),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),57),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),58),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),59),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),60),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fighting"),61),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),62),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),63),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Fire"),64),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),65),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Colorless"),66),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Psychic"),67),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Water"),68),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Lightning"),69),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Grass"),70),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),71),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Trainer"),72),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),73),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),74),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),75),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),76),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Trainer"),77),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),78),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Common"),(SELECT idType FROM tTypes WHERE nom="Trainer"),79),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Rare"),(SELECT idType FROM tTypes WHERE nom="Rainbow"),80),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),81),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Uncommon"),(SELECT idType FROM tTypes WHERE nom="Colorless"),82),
((SELECT idSerie FROM tSeries WHERE nom="Team Rocket"),(SELECT idRarete FROM tRaretes WHERE nom="Holofoil Rare"),(SELECT idType FROM tTypes WHERE nom="Lightning"),83);

INSERT INTO tCartesPokemons
(idPokemon, idCarte, idSpecialite)
VALUES
((SELECT idPokemon FROM tPokemons WHERE nom="Alakazam"),(SELECT idCarte FROM tCartes WHERE numSerie=1 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Arbok"),(SELECT idCarte FROM tCartes WHERE numSerie=2 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Blastoise"),(SELECT idCarte FROM tCartes WHERE numSerie=3 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Charizard"),(SELECT idCarte FROM tCartes WHERE numSerie=4 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Dragonite"),(SELECT idCarte FROM tCartes WHERE numSerie=5 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Dugtrio"),(SELECT idCarte FROM tCartes WHERE numSerie=6 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Golbat"),(SELECT idCarte FROM tCartes WHERE numSerie=7 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Gyarados"),(SELECT idCarte FROM tCartes WHERE numSerie=8 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Hypno"),(SELECT idCarte FROM tCartes WHERE numSerie=9 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Machamp"),(SELECT idCarte FROM tCartes WHERE numSerie=10 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Magneton"),(SELECT idCarte FROM tCartes WHERE numSerie=11 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Slowbro"),(SELECT idCarte FROM tCartes WHERE numSerie=12 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Vileplume"),(SELECT idCarte FROM tCartes WHERE numSerie=13 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Weezing"),(SELECT idCarte FROM tCartes WHERE numSerie=14 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idTrainer FROM tTrainers WHERE nom="Here Comes Team Rocket!"),(SELECT idCarte FROM tCartes WHERE numSerie=15 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Rocket's Sneak Attack"),(SELECT idCarte FROM tCartes WHERE numSerie=16 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idEnergie FROM tEnergies WHERE nom="Rainbow Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=17 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Alakazam"),(SELECT idCarte FROM tCartes WHERE numSerie=18 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Arbok"),(SELECT idCarte FROM tCartes WHERE numSerie=19 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Blastoise"),(SELECT idCarte FROM tCartes WHERE numSerie=20 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Charizard"),(SELECT idCarte FROM tCartes WHERE numSerie=21 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Dragonite"),(SELECT idCarte FROM tCartes WHERE numSerie=22 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Dugtrio"),(SELECT idCarte FROM tCartes WHERE numSerie=23 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Golbat"),(SELECT idCarte FROM tCartes WHERE numSerie=24 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Gyarados"),(SELECT idCarte FROM tCartes WHERE numSerie=25 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Hypno"),(SELECT idCarte FROM tCartes WHERE numSerie=26 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Machamp"),(SELECT idCarte FROM tCartes WHERE numSerie=27 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Magneton"),(SELECT idCarte FROM tCartes WHERE numSerie=28 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Slowbro"),(SELECT idCarte FROM tCartes WHERE numSerie=29 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Vileplume"),(SELECT idCarte FROM tCartes WHERE numSerie=30 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Weezing"),(SELECT idCarte FROM tCartes WHERE numSerie=31 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Charmeleon"),(SELECT idCarte FROM tCartes WHERE numSerie=32 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Dragonair"),(SELECT idCarte FROM tCartes WHERE numSerie=33 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Electrode"),(SELECT idCarte FROM tCartes WHERE numSerie=34 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Flareon"),(SELECT idCarte FROM tCartes WHERE numSerie=35 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Gloom"),(SELECT idCarte FROM tCartes WHERE numSerie=36 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Golduck"),(SELECT idCarte FROM tCartes WHERE numSerie=37 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Jolteon"),(SELECT idCarte FROM tCartes WHERE numSerie=38 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Kadabra"),(SELECT idCarte FROM tCartes WHERE numSerie=39 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Machoke"),(SELECT idCarte FROM tCartes WHERE numSerie=40 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Muk"),(SELECT idCarte FROM tCartes WHERE numSerie=41 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Persian"),(SELECT idCarte FROM tCartes WHERE numSerie=42 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Primeape"),(SELECT idCarte FROM tCartes WHERE numSerie=43 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Rapidash"),(SELECT idCarte FROM tCartes WHERE numSerie=44 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Vaporeon"),(SELECT idCarte FROM tCartes WHERE numSerie=45 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Wartortle"),(SELECT idCarte FROM tCartes WHERE numSerie=46 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Magikarp"),(SELECT idCarte FROM tCartes WHERE numSerie=47 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Porygon"),(SELECT idCarte FROM tCartes WHERE numSerie=48 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Abra"),(SELECT idCarte FROM tCartes WHERE numSerie=49 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Charmander"),(SELECT idCarte FROM tCartes WHERE numSerie=50 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Raticate"),(SELECT idCarte FROM tCartes WHERE numSerie=51 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark")),
((SELECT idPokemon FROM tPokemons WHERE nom="Diglett"),(SELECT idCarte FROM tCartes WHERE numSerie=52 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Dratini"),(SELECT idCarte FROM tCartes WHERE numSerie=53 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Drowzee"),(SELECT idCarte FROM tCartes WHERE numSerie=54 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Eevee"),(SELECT idCarte FROM tCartes WHERE numSerie=55 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Ekans"),(SELECT idCarte FROM tCartes WHERE numSerie=56 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Grimer"),(SELECT idCarte FROM tCartes WHERE numSerie=57 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Koffing"),(SELECT idCarte FROM tCartes WHERE numSerie=58 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Machop"),(SELECT idCarte FROM tCartes WHERE numSerie=59 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Magnemite"),(SELECT idCarte FROM tCartes WHERE numSerie=60 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Mankey"),(SELECT idCarte FROM tCartes WHERE numSerie=61 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Meowth"),(SELECT idCarte FROM tCartes WHERE numSerie=62 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Oddish"),(SELECT idCarte FROM tCartes WHERE numSerie=63 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Ponyta"),(SELECT idCarte FROM tCartes WHERE numSerie=64 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Psyduck"),(SELECT idCarte FROM tCartes WHERE numSerie=65 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Rattata"),(SELECT idCarte FROM tCartes WHERE numSerie=66 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Slowpoke"),(SELECT idCarte FROM tCartes WHERE numSerie=67 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Squirtle"),(SELECT idCarte FROM tCartes WHERE numSerie=68 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Voltorb"),(SELECT idCarte FROM tCartes WHERE numSerie=69 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Zubat"),(SELECT idCarte FROM tCartes WHERE numSerie=70 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Here Comes Team Rocket!"),(SELECT idCarte FROM tCartes WHERE numSerie=71 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Rocket's Sneak Attack"),(SELECT idCarte FROM tCartes WHERE numSerie=72 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="The Boss's Way"),(SELECT idCarte FROM tCartes WHERE numSerie=73 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Challenge!"),(SELECT idCarte FROM tCartes WHERE numSerie=74 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Digger"),(SELECT idCarte FROM tCartes WHERE numSerie=75 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Imposter Oak's Revenge"),(SELECT idCarte FROM tCartes WHERE numSerie=76 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Nightly Garbage Run"),(SELECT idCarte FROM tCartes WHERE numSerie=77 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Goop Gas Attack"),(SELECT idCarte FROM tCartes WHERE numSerie=78 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idTrainer FROM tTrainers WHERE nom="Sleep!"),(SELECT idCarte FROM tCartes WHERE numSerie=79 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idEnergie FROM tEnergies WHERE nom="Rainbow Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=80 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idEnergie FROM tEnergies WHERE nom="Full Heal Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=81 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idEnergie FROM tEnergies WHERE nom="Potion Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=82 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Normal")),
((SELECT idPokemon FROM tPokemons WHERE nom="Raichu"),(SELECT idCarte FROM tCartes WHERE numSerie=83 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")),(SELECT idSpecialite FROM tSpecialites WHERE nom="Dark"));




INSERT INTO tCartesTrainers
(idTrainer, idCarte)
VALUES
((SELECT idTrainer FROM tTrainers WHERE nom="Here Comes Team Rocket!"),(SELECT idCarte FROM tCartes WHERE numSerie=15 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Rocket's Sneak Attack"),(SELECT idCarte FROM tCartes WHERE numSerie=16 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Here Comes Team Rocket!"),(SELECT idCarte FROM tCartes WHERE numSerie=71 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Rocket's Sneak Attack"),(SELECT idCarte FROM tCartes WHERE numSerie=72 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="The Boss's Way"),(SELECT idCarte FROM tCartes WHERE numSerie=73 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Challenge!"),(SELECT idCarte FROM tCartes WHERE numSerie=74 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Digger"),(SELECT idCarte FROM tCartes WHERE numSerie=75 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Imposter Oak's Revenge"),(SELECT idCarte FROM tCartes WHERE numSerie=76 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Nightly Garbage Run"),(SELECT idCarte FROM tCartes WHERE numSerie=77 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Goop Gas Attack"),(SELECT idCarte FROM tCartes WHERE numSerie=78 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idTrainer FROM tTrainers WHERE nom="Sleep!"),(SELECT idCarte FROM tCartes WHERE numSerie=79 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")));

INSERT INTO tCartesEnergies
(idEnergie, idCarte)
VALUES
((SELECT idEnergie FROM tEnergies WHERE nom="Rainbow Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=17 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Rainbow Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=80 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Full Heal Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=81 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket"))),
((SELECT idEnergie FROM tEnergies WHERE nom="Potion Energy"),(SELECT idCarte FROM tCartes WHERE numSerie=82 AND idSerie = (SELECT idSerie FROM tSeries WHERE nom="Team Rocket")));