INSERT INTO tEnergies
(nom)
VALUES
("Fighting Energy"),
("Fire Energy"),
("Grass Energy"),
("Lightning Energy"),
("Psychic Energy"),
("Water Energy"),
("Fairy Energy"),
("Double Colorless Energy"),
("Full Heal Energy"),
("Potion Energy"),
("Rainbow Energy"),
("Darkness Energy"),
("Metal Energy"),
("Recycle Energy"),
("Miracle Energy"),
("Boost Energy"),
("Crystal Energy"),
("Warp Energy"),
("Bounce Energy"),
("Cyclone Energy"),
("Retro Energy"),
("Multi Energy"),
("Double Rainbow Energy"),
("Aqua Energy"),
("Magma Energy"),
("Dark Metal Energy"),
("R Energy"),
("Heal Energy"),
("Scramble Energy"),
("Holon Energy GL"),
("Holon Energy FF"),
("Holon Energy WP"),
("React Energy"),
("&#x03B4 Rainbow Energy"),
("Call Energy"),
("Health Energy"),
("Recover Energy"),
("SP Energy"),
("Upper Energy"),
("Rescue Energy"),
("Prism Energy"),
("Blend Energy GFPD"),
("Blend Energy WLFM"),
("Plasma Energy"),
("Herbal Energy"),
("Strong Energy"),
("Mystery Energy"),
("Shield Energy"),
("Wonder Energy"),
("Double Aqua Energy"),
("Double Magma Energy");